function [objFreqEstimator, objFreqCompensator, objRXFilter] = ...
    initCommsRXSync(modOrder, upsampFactor, sampFreq)

    % Coarse frequency offset estimation and compensation
    objFreqEstimator = comm.PSKCoarseFrequencyEstimator( ...
        'ModulationOrder',     modOrder, ...
        'Algorithm',           'FFT-based', ...
        'FrequencyResolution', 10, ...
        'SampleRate',          sampFreq);
    
    objFreqCompensator = comm.PhaseFrequencyOffset( ...
        'PhaseOffset',           0, ...
        'FrequencyOffsetSource', 'Input port', ...
        'SampleRate',            sampFreq);

    % Create receive filter object
    objRXFilter = comm.RaisedCosineReceiveFilter(...
        'InputSamplesPerSymbol',  upsampFactor, ...
        'DecimationFactor',       1, ...
        'RolloffFactor',          0.25, ...
        'FilterSpanInSymbols',    10);

end